name: Seth Gilpin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6942'
    - '#5e5858'
    - '#ccbcae'
    - '#ffc2b2'
  brandStrength: 0
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 1
purpose: []
