name: Seth Gilpin
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#cf3225'
    - '#f0cf33'
    - '#808080'
  brandStrength: 0.3125
  lightness: 0.0625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
